In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv("drug.csv")

In [3]:
data.head()

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1      condition  \
0           0        148873          149718             73450  Birth Control   
1           1        142496          143318             73600  Birth Control   
2           2        102598          103191             72720  Birth Control   
3           3           559             562             72638  Birth Control   
4           4         73183           73619             16494  Birth Control   

                                              review  rating  \
0  "I loved this pill at first, it got rid if my ...       4   
1  "I started taking the pill a little over a mon...       5   
2  "This is the first pill that I&#039;ve tried w...       7   
3  "I&#039;ve been on Junel Fe for 9 months now. ...       3   
4  "This pill overall is not good. its been about...       2   

                 date  usefulCount                           drugName  
0   November 28, 2013           22  Ethinyl estradiol / norethindrone  
1        May 28, 2013            6  Ethinyl estradiol / norethindrone  
2     August 28, 2015            2  Ethinyl estradiol / norethindrone  
3  September 22, 2015            5  Ethinyl estradiol / norethindrone  
4   December 25, 2015           15  Ethinyl estradiol / norethindrone

In [4]:
data.shape

(18160, 10)

In [5]:
data.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1',
       'condition', 'review', 'rating', 'date', 'usefulCount', 'drugName'],
      dtype='object')

In [6]:
data1=data.dropna()
data1.shape

(18160, 10)

In [7]:
print(data1.head())

   Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1  Unnamed: 0.1.1.1      condition  \
0           0        148873          149718             73450  Birth Control   
1           1        142496          143318             73600  Birth Control   
2           2        102598          103191             72720  Birth Control   
3           3           559             562             72638  Birth Control   
4           4         73183           73619             16494  Birth Control   

                                              review  rating  \
0  "I loved this pill at first, it got rid if my ...       4   
1  "I started taking the pill a little over a mon...       5   
2  "This is the first pill that I&#039;ve tried w...       7   
3  "I&#039;ve been on Junel Fe for 9 months now. ...       3   
4  "This pill overall is not good. its been about...       2   

                 date  usefulCount                           drugName  
0   November 28, 2013           22  Ethinyl estradiol / noreth

In [8]:
data1.drugName.unique()

array(['Ethinyl estradiol / norethindrone', 'Levonorgestrel',
       'Ethinyl estradiol / norgestimate', 'Etonogestrel', 'Nexplanon'],
      dtype=object)

In [9]:
import matplotlib.pyplot as plt
import seaborn as sns


In [10]:
data1.drugName.value_counts()

Ethinyl estradiol / norethindrone    3632
Levonorgestrel                       3632
Ethinyl estradiol / norgestimate     3632
Etonogestrel                         3632
Nexplanon                            3632
Name: drugName, dtype: int64

In [11]:
import re
import string
import nltk
from nltk.corpus import stopwords
stopword=set(stopwords.words('english'))
stemmer = nltk.SnowballStemmer("english")


In [13]:
def clean(text):
    text = str(text).lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    text = [word for word in text.split(' ') if word not in stopword]
    text=" ".join(text)
    text = [stemmer.stem(word) for word in text.split(' ')]
    text=" ".join(text)
    return text
data["review"] = data["review"].apply(clean)

In [14]:
x = np.array(data1["review"])
y = np.array(data1["drugName"])

In [15]:
x

array(['"I loved this pill at first, it got rid if my terrible cramps. A few months after, however, I had two periods each month. Now I have a period every other week. The birth control pill is a hit-or-miss type of business."',
       '"I started taking the pill a little over a month ago and it still makes me feel so nauseous. I bled for a full month and it was heavy some days and light others but the doctor said that was normal. I don&#039;t want to stop taking it because I&#039;m getting married in two months so I&#039;m pushing through the horribleness of it and hoping the nausea goes away eventually. Oh and it makes me so moody too!"',
       '"This is the first pill that I&#039;ve tried which I&#039;ve liked being on; I&#039;ve had no acne, my periods are more manageable with mood swings GREATLY reduced (a blessing). My breasts also grew which I was pleased about as I&#039;m usually a B cup. I had a little soreness from that but not huge amount. The only downside is weight gain. 

In [16]:
y

array(['Ethinyl estradiol / norethindrone',
       'Ethinyl estradiol / norethindrone',
       'Ethinyl estradiol / norethindrone', ..., 'Nexplanon', 'Nexplanon',
       'Nexplanon'], dtype=object)

vector = 1,2,3,,,,,,,
[1
2
3
3]

sca= 6
sca2 = 68

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [18]:
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [19]:
from sklearn.ensemble import RandomFore stClassifier
clf = RandomForestClassifier()
clf.fit(X_train,y_train)
# train input and output
#now my module is in clf

RandomForestClassifier()

In [21]:
#for validating - test input
pre=clf.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score
a = accuracy_score(y_test,pre)*100
print('RandomForestClassifier accuracy:',a)

RandomForestClassifier accuracy: 72.56799599532788


In [23]:
#According to the cross-validated MCC scores, the random forest is the best-performing model, so now let's evaluate its performance on the test set.
from sklearn.metrics import confusion_matrix, classification_report, matthews_corrcoef, cohen_kappa_score, accuracy_score, average_precision_score, roc_auc_score

cm1=confusion_matrix(y_test,pre)
print('Confusion Matrix result of Decision Tree Classifier is:\n',cm1)
print("")
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )
print("")
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)
print("")

Confusion Matrix result of Decision Tree Classifier is:
 [[1015  137   10   19    2]
 [ 170  992    3   15    4]
 [  45    9  532   33  575]
 [  20   11   23 1173    6]
 [  11    6  540    5  637]]

Sensitivity :  0.8810763888888888

Specificity :  0.8537005163511188



In [24]:
input_word=input("ENTER THE SENTENCE:")

ENTER THE SENTENCE:"I loved this pill at first, it got rid if my terrible cramps. A few months after, however, I had two periods each month. Now I have a period every other week. The birth control pill is a hit-or-miss type of business."


In [25]:
data = cv.transform([input_word]).toarray()
print(clf.predict(data))

['Ethinyl estradiol / norethindrone']
